### ISSUE TITLE
Multiple language support for action bar messages, biomes and the user interface

### ISSUE THREAD

**Issue by rusthero** [rusthero/BiomeCompass#1]
I'm not a fan of making all messages configurable like in most plugins. Instead, I think it would be better to have multiple translations available and make them selectable through config.yml, like this:

```YAML
# Biome Compass Configuration File
# Check wiki to learn more https://github.com/rusthero/BiomeCompass/wiki

cooldown: 5
resolution: 32
radius: 6400
cacheSize: 100
...
language: en
```

This would provide server owners with a more streamlined and faster experience. I'm open to other suggestions and this is not a final proposal.
